### ISSUE TITLE
Get 2016 Election Data for Foco/Larimer

### ISSUE THREAD

**Issue by DanLaRoche** [CodeForFoco/CERP#1]
We have a contact at the City of Fort Collins who has access to the elections people for the city, and potentially county contacts. We need to get election data per precinct for at least the presidential election, and hopefully for state and local issues as well.

Olivia Terrell
oterrell@fcgov.com
970-416-2282
215 N. Mason St.

**Comment by JordanMajd** [comment]
Done!
