### ISSUE TITLE
Layout UX Design

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/CERP#19]
Draft a design for the look and feel with the project, potentially with a local designer.

**Comment by sirbugsbunny** [comment]
hey, do you need help?

**Comment by JordanMajd** [comment]
Thanks for reaching out - Possibly, @DanLaRoche and @deidyomega might have some thoughts.

**Comment by JordanMajd** [comment]
Moved issue to [CERP-webview](https://github.com/CodeForFoco/CERP-webview/) repo.
