### ISSUE TITLE
Heatmap has revealed data issues

### ISSUE THREAD

**Issue by deidyomega** [CodeForFoco/CERP#21]
All the areas below that are grey are areas defined in the Larimer County geodata, however aren't shown in the [PresidentialElection.json](https://github.com/deidyomega/CERP/blob/master/cerp/static/2016-PresidentialElection.json) file.
![screenshot from 2017-10-21 21-47-47](https://user-images.githubusercontent.com/943559/31857976-bb677b40-b6a9-11e7-830d-324834db7656.png)

Live example here: http://cerp-code-foco.herokuapp.com/#/

**Comment by deidyomega** [comment]
I created a unit test for the data, and it currently fails, once it passes we know we have good data.

Run: `sh test.sh` after you've made some changes.

AssertionError: Items in the `VoterPrecinct.geojson` but not `2016-PresidentialElection.json`: 
'2145335338'
'2145235241'
'2234935812'
'2145335342'
'2154935436'
'2145235245'
'2155135549'
'2145235242'
'2154935438'
'2145335341'
'2154935441'
'2154935439'
'2234935813'
'2145335344'
'2145335343'
'2145335340'
'2234935811'
'2145235246'
'2155135545'
'2155135544'
'2154935437'
'2145235243'
'2155135546'
'2154935435'
'2155135548'
'2234935814'
'2145335337'
'2145235244'
'2145235247'
'2145335339'
'2154935440'
'2155135547'

**Comment by deidyomega** [comment]
Spot checked: `2154935436`, and found it isn't in the SOVC-rotated.pdf file at all.  Did the precincts change?  If so, how can we get the shp file for the precincts on the date of the election?
![screenshot from 2017-10-23 00-24-58](https://user-images.githubusercontent.com/943559/31874843-9cd6da06-b788-11e7-8d59-3363ab948a4d.png)

**Comment by bengowan** [comment]
Not sure if this is helpful, given the mismatch is between the current precint geo data and the 2016 results, but here is a page from larimer of historic SOVC pdfs going back quite a few years:  https://www.larimer.org/clerk/elections/records-data/past-info/results

**Comment by bengowan** [comment]
This may be a bit closer, a June 1, 2017 dated precinct map (it has the first "missing" precinct number, 2145335338)  
 ftp://sftp.larimer.org/GISData/GIS_StandardMaps/Elections2015/Votpre_clr_NORTH.pdf

Oddly found under a 2015 Elections folder at the county site.

**Comment by deidyomega** [comment]
We could manually spot check those pdf's see if they show if the precincts have changed, but without the shape files, I doubt anyone here is going to manually copy those shapes over...

Good find though!
