### ISSUE TITLE
Slim down geojson

### ISSUE THREAD

**Issue by abettermap** [CodeForFoco/CERP#27]
It's kinda meaty, ~2ish MB now. Make it smaller via:

- [x] Remove unneeded fields (e.g. `SHAPE_LEN`, etc.)
- [x] Simplify/reduce vertices
- [x] Reduce coordinate precision (e.g. `40.374187379751248` to `40.37419`)
- [x] Minify and commit

Other:
- [ ] Test it: zoom in really far, see if vertices look suffish
- [x] Screenshot the old-vs-new savings (just cuz)
- [ ] Document procedures (use `ogr2ogr` if no Node-based modules available)

**Wishlist:** topojson!

**Comment by abettermap** [comment]
### Savings 
Almost **90%**:
![image](https://user-images.githubusercontent.com/4974087/32984807-a2e5ac82-cc6a-11e7-9810-56b4b9ca4906.png)

### Still precise enough?
If not, I can slim it down more, but this project deals with large precinct-level data so probably fine as-is. Still looks deese around `1:27000` scale:

![image](https://user-images.githubusercontent.com/4974087/32984790-66f39d88-cc6a-11e7-9da5-9b15cceba7cc.png)
 
...albeit a bit rougher at `1:6900`:

![image](https://user-images.githubusercontent.com/4974087/32984799-7fc14a7c-cc6a-11e7-9483-a854742a2146.png)

### TopoJSON savings
Just for shits and giggles (mostly giggles), `topojson` cuts the slimmed GeoJSON by another 50%:

![image](https://user-images.githubusercontent.com/4974087/32984822-d08c4aec-cc6a-11e7-95f2-420cc730658a.png)

We would need to adapt the MapBox code to handle it, but it's plenty doable.

**Comment by deidyomega** [comment]
Considering the size reduction.  I think it's close enough.  This isn't for land surveying, this is for getting a general idea.

Great work!
