### ISSUE TITLE
Document API Endpoints

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/CERP#31]
Document the API endpoints. 

Bonus points: consider automated solutions so that as the API evolves we don't need to continue to update the docs. One example would be utilizing build tooling with  javadoc style method comments to generate markdown.

Future: expose the documentation on the front end side of the website.

**Comment by deidyomega** [comment]
With python, you can use sphinx to automatically document endpoints.
http://www.sphinx-doc.org/en/stable/

Right now, all the endpoints are viewable by going to the root, however, that doesn't describe what each endpoint does, or how to use it.
